### ISSUE TITLE
Permission error in Rank.js due to managed roles

### ISSUE THREAD

**Issue by LaughLax** [LaughLax/icarus5#96]
DiscordAPIError: Missing Permissions
at RequestHandler.execute (/home/ryndinovaia/icarus5/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async RequestHandler.push (/home/ryndinovaia/icarus5/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
at async GuildMemberManager.edit (/home/ryndinovaia/icarus5/node_modules/discord.js/src/managers/GuildMemberManager.js:279:15)
at async Timeout._onTimeout (/home/ryndinovaia/icarus5/modules/rank.js:163:19)

**Comment by LaughLax** [comment]
Source of issue discovered - user has the Nitro Booster role, which can't be manually assigned or removed.
